version: "3.9"
   
services:
  elasticsearch:
    image: elasticsearch:7.8.1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=my_database
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    depends_on:
      - db  
      - elasticsearch
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_NAME=my_database
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    ports:
      - '5433:5432'
    volumes: 
      - postgres_data:/var/lib/postgresql/data/


volumes:
  postgres_data:

