# Generated by Django 4.1 on 2022-10-12 06:09

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elasticdemo',
            name='book_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elasticdemo',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elasticdemo',
            name='price',
            field=models.CharField(default=datetime.datetime(2022, 10, 12, 6, 9, 54, 391834, tzinfo=datetime.timezone.utc), max_length=70),
            preserve_default=False,
        ),
    ]
